/**
 * jailguard.h — C ABI for the JailGuard prompt-injection detector.
 *
 * Generated by cbindgen from src/c_api.rs. DO NOT EDIT MANUALLY.
 *
 * Stable across MAJOR versions of jailguard. See c_api.rs for the
 * full error-code table and memory-ownership contract.
 *
 * Note: a duplicate `#define EMBEDDING_DIM 384` may appear in this
 * file due to cbindgen scanning private consts in adjacent modules.
 * The two definitions are identical in value, so the duplicate is
 * harmless (modulo a -Wduplicate-define preprocessor warning).
 */


#ifndef JAILGUARD_H
#define JAILGUARD_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation succeeded.
 */
#define JAILGUARD_OK 0

/**
 * Null pointer or invalid UTF-8 in input string.
 */
#define JAILGUARD_INVALID_INPUT 1

/**
 * ONNX model download failed (network error or checksum mismatch).
 */
#define JAILGUARD_DOWNLOAD_FAILED 2

/**
 * Inference or classification failed (corrupt session, OOM, etc.).
 */
#define JAILGUARD_INFERENCE_FAILED 3

/**
 * Internal error — likely a logic bug. Please file an issue.
 */
#define JAILGUARD_INTERNAL_ERROR 99

#define EMBEDDING_DIM 384

/**
 * Embedding dimension for all-MiniLM-L6-v2
 */
#define EMBEDDING_DIM 384

/**
 * Maximum sequence length for the model
 */
#define MAX_SEQ_LENGTH 256

/**
 * Risk classification bucket. Matches the Rust [`RiskLevel`] and the
 * Python `RiskLevel` enum value-for-value.
 */
typedef enum jailguard_risk_t {
  /**
   * Score < 0.3 — almost certainly benign.
   */
  Safe = 0,
  /**
   * 0.3 ≤ score < 0.5 — probably benign but worth monitoring.
   */
  Low = 1,
  /**
   * 0.5 ≤ score < 0.7 — possible injection, review recommended.
   */
  Medium = 2,
  /**
   * 0.7 ≤ score < 0.9 — likely injection.
   */
  High = 3,
  /**
   * score ≥ 0.9 — almost certainly an injection.
   */
  Critical = 4,
} jailguard_risk_t;

/**
 * Output of [`jailguard_detect`].
 */
typedef struct jailguard_detection_result_t {
  /**
   * 1 if classified as injection, 0 otherwise.
   */
  int is_injection;
  /**
   * Raw model probability in [0.0, 1.0].
   */
  float score;
  /**
   * Confidence (always ≥ 0.5). Equals score for injections,
   * 1.0 - score for benigns.
   */
  float confidence;
  /**
   * Risk bucket derived from score.
   */
  enum jailguard_risk_t risk;
} jailguard_detection_result_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the JailGuard library version string (matches `Cargo.toml`).
 *
 * The returned pointer is to a static, NUL-terminated string and must
 * not be freed.
 */
 const char *jailguard_version(void) ;

/**
 * Pre-download the ONNX embedding model (~90 MB) to the cache directory.
 *
 * Idempotent — does nothing if the model is already cached. Returns
 * [`JAILGUARD_OK`] on success or [`JAILGUARD_DOWNLOAD_FAILED`] otherwise.
 *
 * Calling this at startup avoids first-detection latency for the
 * download (typically ~2–10 seconds).
 */
 int jailguard_download_model(void) ;

/**
 * Get the path to the ONNX model cache directory.
 *
 * The returned string is owned by the caller and must be freed with
 * [`jailguard_free_string`]. Returns null on internal error.
 */
 char *jailguard_model_cache_dir(void) ;

/**
 * Free a string returned by the JailGuard C API.
 *
 * SAFETY: `s` must have been returned by a `jailguard_*` function that
 * documents its return value as caller-owned. Must not be called twice
 * on the same pointer. Null is a no-op.
 */
 void jailguard_free_string(char *s) ;

/**
 * Detect whether `text` is a prompt injection.
 *
 * Writes the result to `*out` on success.
 *
 * SAFETY: `text` must be a valid NUL-terminated C string. `out` must
 * be a valid, properly aligned pointer to a `jailguard_detection_result_t`.
 */
 int jailguard_detect(const char *text, struct jailguard_detection_result_t *out) ;

/**
 * Quick boolean injection check. Writes `0` or `1` to `*out`.
 *
 * SAFETY: `text` valid C string; `out` valid pointer to `c_int`.
 */
 int jailguard_is_injection(const char *text, int *out) ;

/**
 * Get the raw injection probability in [0.0, 1.0].
 *
 * SAFETY: `text` valid C string; `out` valid pointer to `c_float`.
 */
 int jailguard_score(const char *text, float *out) ;

/**
 * Detect prompt injection on a batch of texts.
 *
 * `texts` is an array of `count` NUL-terminated C string pointers.
 * `out` is a pre-allocated array of `count` result slots that will be
 * written in order. The output array must be at least `count` long;
 * the caller owns the storage.
 *
 * SAFETY:
 * - `texts` must be a valid array of `count` valid C string pointers
 *   (each element must satisfy the contract of [`jailguard_detect`]).
 * - `out` must be a valid array of at least `count` results.
 */

int jailguard_detect_batch(const char *const *texts,
                           uintptr_t count,
                           struct jailguard_detection_result_t *out)
;

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* JAILGUARD_H */
